#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "lib"))

from bootstrap import install_steps as managed_install_steps, run_install as run_managed_install  # noqa: E402
from install_tui import Step, open_tui  # noqa: E402


LIVE_CONFIG_PATH = Path.home() / ".codex" / "config.toml"
ADOPTED_CONFIG_PATH = REPO_ROOT / "codex" / "config" / "80-adopted.toml"
LOCAL_CONFIG_OVERLAY_PATH = REPO_ROOT / "codex" / "config" / "90-local.toml"
COMPONENT_STATE_PATH = REPO_ROOT / ".state" / "components.toml"
REQUIRED_FORMULAS = ["python", "ripgrep", "node", "pnpm", "uv", "jq"]


def install_steps() -> List[Step]:
    return managed_install_steps()

def find_brew() -> Optional[str]:
    if shutil_which("brew"):
        return shutil_which("brew")
    for candidate in ("/opt/homebrew/bin/brew", "/usr/local/bin/brew"):
        if Path(candidate).exists():
            return candidate
    return None


def shutil_which(name: str) -> Optional[str]:
    for part in os.environ.get("PATH", "").split(":"):
        if not part:
            continue
        candidate = Path(part) / name
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def plain_prompt_yes_no(prompt: Sequence[str], *, default: bool) -> bool:
    prompt_text = "\n".join(prompt)
    suffix = "[Y/n]" if default else "[y/N]"
    reply = input("{}\n{} ".format(prompt_text, suffix)).strip().lower()
    if not reply:
        return default
    return reply in ("y", "yes")


def prompt_yes_no(prompt: Sequence[str], *, default: bool, non_interactive: bool, ui) -> bool:
    if non_interactive or not sys.stdin.isatty():
        return default
    if ui is not None:
        return ui.prompt_yes_no(prompt, default=default)
    return plain_prompt_yes_no(prompt, default=default)


def config_is_managed() -> bool:
    if not LIVE_CONFIG_PATH.exists():
        return False
    try:
        return "Generated by codex-spine" in LIVE_CONFIG_PATH.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def jcodemunch_already_enabled() -> bool:
    for path in (LOCAL_CONFIG_OVERLAY_PATH, COMPONENT_STATE_PATH):
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "jcodemunch-mcp" in text or "[mcp_servers.jcodemunch]" in text:
            return True
    return False


def brew_formula_installed(brew_path: str, formula: str) -> bool:
    result = subprocess.run([brew_path, "list", "--versions", formula], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return result.returncode == 0


def preflight_existing_config(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.set_step(0, note="Checking whether there are existing Codex settings to carry forward.")
    if not LIVE_CONFIG_PATH.exists():
        if ui is not None:
            ui.finish_step(0, status="ok", note="No existing Codex settings need to be carried forward.")
        return
    if config_is_managed():
        if ui is not None:
            ui.finish_step(0, status="ok", note="Your current Codex settings are already managed here.")
        return
    if non_interactive or not sys.stdin.isatty():
        raise RuntimeError(
            "Found an existing unmanaged Codex config at {}. Rerun interactively so codex-spine can import the settings you want to keep into {} before it makes broader install changes.".format(
                LIVE_CONFIG_PATH, ADOPTED_CONFIG_PATH
            )
        )
    accepted = prompt_yes_no(
        [
            "Found an existing Codex config:",
            "  {}".format(LIVE_CONFIG_PATH),
            "",
            "codex-spine can preserve the rest of your settings by importing them into:",
            "  {}".format(ADOPTED_CONFIG_PATH),
            "",
            "If you decline, install stops before Homebrew packages, managed wrappers, shell files, launchd, or the live Codex config change.",
        ],
        default=True,
        non_interactive=non_interactive,
        ui=ui,
    )
    if not accepted:
        raise RuntimeError("Leaving the existing Codex config in place. codex-spine stopped before making broader install changes.")
    os.environ["CODEX_SPINE_CONFIG_ADOPTION_APPROVED"] = "1"
    if ui is not None:
        ui.finish_step(0, status="ok", note="Your current Codex settings will be carried into this install.")


def preflight_optional_jcodemunch(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.set_step(1, note="Choosing whether to include optional indexed code navigation.")
    if jcodemunch_already_enabled():
        if ui is not None:
            ui.finish_step(1, status="ok", note="Optional jCodeMunch support is already turned on.")
        return
    if non_interactive or not sys.stdin.isatty():
        if ui is not None:
            ui.finish_step(1, status="ok", note="Optional jCodeMunch support stays off by default in non-interactive runs.")
        return
    include_component = prompt_yes_no(
        [
            "Optional component: jCodeMunch MCP",
            "",
            "If you want indexed code navigation, codex-spine can include the optional jCodeMunch MCP integration in this install.",
            "Later in the install, codex-spine will still fetch the pinned upstream terms and require explicit acknowledgement before enabling it.",
        ],
        default=True,
        non_interactive=non_interactive,
        ui=ui,
    )
    os.environ["CODEX_SPINE_JCODEMUNCH_CHOICE"] = "enable" if include_component else "skip"
    if ui is not None:
        note = (
            "Optional jCodeMunch setup will be offered later in the install."
            if include_component
            else "Optional jCodeMunch support will be skipped for now."
        )
        ui.finish_step(1, status="ok", note=note)


def ensure_homebrew_and_runtime(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.set_step(2, note="Checking for Homebrew and any missing required formulae.")
    brew_path = find_brew()
    if brew_path is None:
        approved = prompt_yes_no(
            [
                "Homebrew is not installed yet.",
                "codex-spine will install Homebrew first, then these baseline formulae:",
                *["  - {}".format(formula) for formula in REQUIRED_FORMULAS],
            ],
            default=True,
            non_interactive=non_interactive,
            ui=ui,
        )
        if not approved:
            raise RuntimeError("codex-spine needs Homebrew plus a small set of Homebrew packages. Install Homebrew from https://brew.sh, then rerun `make install`.")
        os.environ["CODEX_SPINE_BREW_INSTALL_APPROVED"] = "1"
        installer_url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
        with tempfile.NamedTemporaryFile(prefix="codex-spine-homebrew-", suffix=".sh", delete=False) as handle:
            installer_path = Path(handle.name)
        try:
            if ui is not None:
                ui.status("info", "Installing Homebrew now.")
                ui.run_command(["curl", "-fL", installer_url, "-o", str(installer_path)])
                ui.run_bottom_prompt_command(
                    ["sudo", "-v"],
                    panel_title="",
                    intro_lines=[
                        "macOS needs your password before Homebrew can be installed.",
                    ],
                )
                installer_env = os.environ.copy()
                installer_env["NONINTERACTIVE"] = "1"
                ui.run_command(
                    ["/bin/bash", str(installer_path)],
                    env=installer_env,
                    heartbeat_message="Homebrew install is still running...",
                )
            else:
                subprocess.run(["curl", "-fL", installer_url, "-o", str(installer_path)], check=True)
                subprocess.run(["/bin/bash", str(installer_path)], check=True)
        finally:
            installer_path.unlink(missing_ok=True)
        brew_path = find_brew()
        if brew_path is None:
            raise RuntimeError("Homebrew finished installing, but `brew` is still not available in this shell. Open a new shell or run the Homebrew shellenv snippet, then rerun `make install`.")
    missing = [formula for formula in REQUIRED_FORMULAS if not brew_formula_installed(brew_path, formula)]
    if missing:
        approved = True
        if os.environ.get("CODEX_SPINE_BREW_INSTALL_APPROVED") != "1":
            approved = prompt_yes_no(
                [
                    "codex-spine needs these Homebrew packages to continue:",
                    *["  - {}".format(formula) for formula in missing],
                ],
                default=True,
                non_interactive=non_interactive,
                ui=ui,
            )
        if not approved:
            raise RuntimeError("Missing required Homebrew packages: {}. Install them and rerun `make install`.".format(", ".join(missing)))
        os.environ["CODEX_SPINE_BREW_INSTALL_APPROVED"] = "1"
        if ui is not None:
            ui.status("info", "Installing the remaining required formulae.")
            ui.run_command([brew_path, "install"] + missing, heartbeat_message="Homebrew is still installing required formulae...")
        else:
            subprocess.run([brew_path, "install"] + missing, check=True)
    if ui is not None:
        ui.finish_step(2, status="ok", note="The required tools are ready.")


def continue_into_managed_install(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.status("info", "Moving on to qmd and the rest of the codex-spine tools.")
        ui.reconfigure(
            title="codex-spine installer",
            subtitle="",
            clear_logs=True,
        )
    os.environ["CODEX_SPINE_PREFLIGHT_COMPLETED"] = "1"
    os.environ["CODEX_SPINE_PYTHON"] = sys.executable
    run_managed_install(non_interactive=non_interactive, ui=None if non_interactive else ui)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--non-interactive", action="store_true")
    args = parser.parse_args()
    non_interactive = args.non_interactive or not sys.stdin.isatty()
    title = "codex-spine installer"
    subtitle = ""
    ui = None
    try:
        with open_tui(title=title, subtitle=subtitle, steps=install_steps()) as ui:
            preflight_existing_config(non_interactive=non_interactive, ui=None if non_interactive else ui)
            preflight_optional_jcodemunch(non_interactive=non_interactive, ui=None if non_interactive else ui)
            ensure_homebrew_and_runtime(non_interactive=non_interactive, ui=None if non_interactive else ui)
            continue_into_managed_install(non_interactive=non_interactive, ui=None if non_interactive else ui)
    except RuntimeError as exc:
        if ui is not None and not non_interactive:
            ui.fail_step(ui.current_step, note="Install stopped before the next stage.")
            ui.show_message(
                [
                    "Preflight stopped:",
                    "",
                    str(exc),
                ],
                prompt_hint="Press Enter to exit",
            )
        print("ERROR: {}".format(exc), file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        if ui is not None and not non_interactive:
            ui.fail_step(ui.current_step, note="A command failed before Stage 2 could start.")
            ui.show_message(
                [
                    "A preflight command failed:",
                    "",
                    "Command: {}".format(" ".join(exc.cmd)),
                    "Exit status: {}".format(exc.returncode),
                    "",
                    "See the terminal output above for the failing command details.",
                ],
                prompt_hint="Press Enter to exit",
            )
        print("ERROR: command failed with exit status {}: {}".format(exc.returncode, " ".join(exc.cmd)), file=sys.stderr)
        print("See output above for details.", file=sys.stderr)
        return exc.returncode or 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
