#!/usr/bin/env python3

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import List, Optional, Sequence

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "lib"))

from install_tui import Step, open_tui  # noqa: E402


PYTHON_LAUNCHER = REPO_ROOT / "bin" / "codex-python"
STAGE1_BOOTSTRAP = REPO_ROOT / "scripts" / "bootstrap.py"
LIVE_CONFIG_PATH = Path.home() / ".codex" / "config.toml"
ADOPTED_CONFIG_PATH = REPO_ROOT / "codex" / "config" / "80-adopted.toml"
LOCAL_CONFIG_OVERLAY_PATH = REPO_ROOT / "codex" / "config" / "90-local.toml"
COMPONENT_STATE_PATH = REPO_ROOT / ".state" / "components.toml"
REQUIRED_FORMULAS = ["python", "ripgrep", "node", "pnpm", "uv", "jq"]


def install_steps() -> List[Step]:
    return [
        Step("Step 1 of 4", "Existing config", "Protect an unmanaged Codex config before broader install changes."),
        Step("Step 2 of 4", "Optional add-ons", "Decide whether to include optional indexed code navigation later in the install."),
        Step("Step 3 of 4", "Homebrew and runtime", "Install Homebrew if needed, then establish the managed formula and Python floor."),
        Step("Step 4 of 4", "Launch managed installer", "Hand off to the managed Python installer once the runtime floor is ready."),
    ]

def find_brew() -> Optional[str]:
    if shutil_which("brew"):
        return shutil_which("brew")
    for candidate in ("/opt/homebrew/bin/brew", "/usr/local/bin/brew"):
        if Path(candidate).exists():
            return candidate
    return None


def shutil_which(name: str) -> Optional[str]:
    for part in os.environ.get("PATH", "").split(":"):
        if not part:
            continue
        candidate = Path(part) / name
        if candidate.exists() and os.access(candidate, os.X_OK):
            return str(candidate)
    return None


def plain_prompt_yes_no(prompt: Sequence[str], *, default: bool) -> bool:
    prompt_text = "\n".join(prompt)
    suffix = "[Y/n]" if default else "[y/N]"
    reply = input("{}\n{} ".format(prompt_text, suffix)).strip().lower()
    if not reply:
        return default
    return reply in ("y", "yes")


def prompt_yes_no(prompt: Sequence[str], *, default: bool, non_interactive: bool, ui) -> bool:
    if non_interactive or not sys.stdin.isatty():
        return default
    if ui is not None:
        return ui.prompt_yes_no(prompt, default=default)
    return plain_prompt_yes_no(prompt, default=default)


def config_is_managed() -> bool:
    if not LIVE_CONFIG_PATH.exists():
        return False
    try:
        return "Generated by codex-spine" in LIVE_CONFIG_PATH.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False


def jcodemunch_already_enabled() -> bool:
    for path in (LOCAL_CONFIG_OVERLAY_PATH, COMPONENT_STATE_PATH):
        if not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="replace")
        except OSError:
            continue
        if "jcodemunch-mcp" in text or "[mcp_servers.jcodemunch]" in text:
            return True
    return False


def brew_formula_installed(brew_path: str, formula: str) -> bool:
    result = subprocess.run([brew_path, "list", "--versions", formula], check=False, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return result.returncode == 0


def preflight_existing_config(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.set_step(0, note="Checking whether a live Codex config needs adoption before install continues.")
    if not LIVE_CONFIG_PATH.exists():
        if ui is not None:
            ui.finish_step(0, status="ok", note="No existing live Codex config was found.")
        return
    if config_is_managed():
        if ui is not None:
            ui.finish_step(0, status="ok", note="The existing live Codex config is already managed by codex-spine.")
        return
    if non_interactive or not sys.stdin.isatty():
        raise RuntimeError(
            "Found an existing unmanaged Codex config at {}. Rerun interactively so codex-spine can import the settings you want to keep into {} before it makes broader install changes.".format(
                LIVE_CONFIG_PATH, ADOPTED_CONFIG_PATH
            )
        )
    accepted = prompt_yes_no(
        [
            "Found an existing Codex config:",
            "  {}".format(LIVE_CONFIG_PATH),
            "",
            "codex-spine can preserve the rest of your settings by importing them into:",
            "  {}".format(ADOPTED_CONFIG_PATH),
            "",
            "If you decline, install stops before Homebrew packages, managed wrappers, shell files, launchd, or the live Codex config change.",
        ],
        default=True,
        non_interactive=non_interactive,
        ui=ui,
    )
    if not accepted:
        raise RuntimeError("Leaving the existing Codex config in place. codex-spine stopped before making broader install changes.")
    os.environ["CODEX_SPINE_CONFIG_ADOPTION_APPROVED"] = "1"
    if ui is not None:
        ui.finish_step(0, status="ok", note="The existing live config will be adopted into the local overlay during Stage 2.")


def preflight_optional_jcodemunch(*, non_interactive: bool, ui) -> None:
    if ui is not None:
        ui.set_step(1, note="Deciding whether to include the optional jCodeMunch MCP path later in the install.")
    if jcodemunch_already_enabled():
        if ui is not None:
            ui.finish_step(1, status="ok", note="Optional jCodeMunch MCP is already enabled.")
        return
    if non_interactive or not sys.stdin.isatty():
        if ui is not None:
            ui.finish_step(1, status="ok", note="Non-interactive mode keeps the optional jCodeMunch MCP path disabled by default.")
        return
    include_component = prompt_yes_no(
        [
            "Optional component: jCodeMunch MCP",
            "",
            "If you want indexed code navigation, codex-spine can include the optional jCodeMunch MCP integration in this install.",
            "Later in the install, codex-spine will still fetch the pinned upstream terms and require explicit acknowledgement before enabling it.",
        ],
        default=True,
        non_interactive=non_interactive,
        ui=ui,
    )
    os.environ["CODEX_SPINE_JCODEMUNCH_CHOICE"] = "enable" if include_component else "skip"
    if ui is not None:
        note = (
            "Optional jCodeMunch MCP will be offered during Stage 2."
            if include_component
            else "Optional jCodeMunch MCP will be skipped for now."
        )
        ui.finish_step(1, status="ok", note=note)


def ensure_homebrew_and_runtime(*, non_interactive: bool, ui) -> str:
    if ui is not None:
        ui.set_step(2, note="Checking Homebrew and installing the baseline formulas inside the fullscreen preflight.")
    brew_path = find_brew()
    if brew_path is None:
        approved = prompt_yes_no(
            [
                "Homebrew is not installed yet.",
                "codex-spine will install Homebrew first, then these baseline packages:",
                *["  - {}".format(formula) for formula in REQUIRED_FORMULAS],
            ],
            default=True,
            non_interactive=non_interactive,
            ui=ui,
        )
        if not approved:
            raise RuntimeError("codex-spine needs Homebrew plus a small set of Homebrew packages. Install Homebrew from https://brew.sh, then rerun `make install`.")
        installer_url = "https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh"
        with tempfile.NamedTemporaryFile(prefix="codex-spine-homebrew-", suffix=".sh", delete=False) as handle:
            installer_path = Path(handle.name)
        try:
            if ui is not None:
                ui.status("info", "Installing Homebrew inside the preflight runtime.")
                ui.run_command(["curl", "-fL", installer_url, "-o", str(installer_path)])
                ui.run_command(["/bin/bash", str(installer_path)])
            else:
                subprocess.run(["curl", "-fL", installer_url, "-o", str(installer_path)], check=True)
                subprocess.run(["/bin/bash", str(installer_path)], check=True)
        finally:
            installer_path.unlink(missing_ok=True)
        brew_path = find_brew()
        if brew_path is None:
            raise RuntimeError("Homebrew finished installing, but `brew` is still not available in this shell. Open a new shell or run the Homebrew shellenv snippet, then rerun `make install`.")
    missing = [formula for formula in REQUIRED_FORMULAS if not brew_formula_installed(brew_path, formula)]
    if missing:
        approved = True
        if os.environ.get("CODEX_SPINE_BREW_INSTALL_APPROVED") != "1":
            approved = prompt_yes_no(
                [
                    "codex-spine needs these Homebrew packages to continue:",
                    *["  - {}".format(formula) for formula in missing],
                ],
                default=True,
                non_interactive=non_interactive,
                ui=ui,
            )
        if not approved:
            raise RuntimeError("Missing required Homebrew packages: {}. Install them and rerun `make install`.".format(", ".join(missing)))
        os.environ["CODEX_SPINE_BREW_INSTALL_APPROVED"] = "1"
        if ui is not None:
            ui.status("info", "Installing the baseline Homebrew formulas before Stage 2 begins.")
            ui.run_command([brew_path, "install"] + missing, heartbeat_message="Homebrew is still installing baseline formulas...")
        else:
            subprocess.run([brew_path, "install"] + missing, check=True)
    python_bin = resolve_managed_python()
    if python_bin is None:
        raise RuntimeError("Homebrew Python installed, but codex-spine still could not locate Python 3.11+. Rerun `make install` after confirming Homebrew Python is installed.")
    if ui is not None:
        ui.finish_step(2, status="ok", note="Managed runtime is ready at {}.".format(python_bin))
    return python_bin


def resolve_managed_python() -> Optional[str]:
    result = subprocess.run([str(PYTHON_LAUNCHER), "--resolve"], check=False, capture_output=True, text=True)
    if result.returncode != 0:
        return None
    return (result.stdout or "").strip() or None


def exec_stage1(*, managed_python: str, args: Sequence[str], ui) -> None:
    if ui is not None:
        ui.set_step(3, note="Switching from the stock Python preflight to the managed Python installer.")
        ui.finish_step(3, status="ok", note="Launching Stage 2 with {}.".format(managed_python))
        ui.footer = "Launching the managed Python installer..."
        ui.render()
        time_sleep()
        ui.close()
    os.environ["CODEX_SPINE_STAGE_SPLIT_RUNTIME"] = "1"
    os.execvpe(managed_python, [managed_python, str(STAGE1_BOOTSTRAP)] + list(args), os.environ.copy())


def time_sleep() -> None:
    import time

    time.sleep(0.3)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--non-interactive", action="store_true")
    args, passthrough = parser.parse_known_args()
    non_interactive = args.non_interactive or not sys.stdin.isatty()
    title = "codex-spine preflight runtime"
    subtitle = "Stage 1 of 2: stock macOS Python drives first-run install before the managed runtime takes over."
    try:
        with open_tui(title=title, subtitle=subtitle, steps=install_steps()) as ui:
            preflight_existing_config(non_interactive=non_interactive, ui=None if non_interactive else ui)
            preflight_optional_jcodemunch(non_interactive=non_interactive, ui=None if non_interactive else ui)
            managed_python = ensure_homebrew_and_runtime(non_interactive=non_interactive, ui=None if non_interactive else ui)
            exec_stage1(managed_python=managed_python, args=passthrough + (["--non-interactive"] if non_interactive and "--non-interactive" not in passthrough else []), ui=None if non_interactive else ui)
    except RuntimeError as exc:
        print("ERROR: {}".format(exc), file=sys.stderr)
        return 1
    except subprocess.CalledProcessError as exc:
        print("ERROR: command failed with exit status {}: {}".format(exc.returncode, " ".join(exc.cmd)), file=sys.stderr)
        print("See output above for details.", file=sys.stderr)
        return exc.returncode or 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
